<?php

/**
 * Created by PhpStorm.
 * User: zk
 * Date: 2020/2/21
 * Time: 14:45
 */

namespace app\model;
use think\Model;

class User extends Model
{

    //设置模型名称
    protected $name = 'user';

    //设置表名
    protected $table = '';

    //设置主键
    protected $pk = 'user_id';

    //模型初始化 需要使用static静态方法
    protected static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }


}